#' @title Parsing raw WhatsApp Chat Textfiles accoring to iOs text structure
#'
#' @description Creates a dataframe from an exported WhatsApp textfile containing one row per message
#' and a column for DateTime when the message was send, name of the sender and body of the message.
#' @param UnparsedChat The name of the exported Whatsapp textfile to be parsed as a character string
#' @param nl Character string defining character for newline indicators. Default is a unicode newline
#' @param mediaindicator Character string for detecting media and file attachments
#' @param mediaomitted Character string inserted by WhatsApp instead of filenames when not exporting media
#' @param sentlocation Regex for detecting autogenerated messages for locations shared via chat
#' @param livelocation Regex for detecting autogenerated messages for locations shared via chat
#' @param datetimeindicator Regex for detecting the DateTime indicator at the beginning of each message
#' @param nlreplace Replacement string for a newline character in parsed message. Default is " start_newline "
#' @param mediareplace Replacement string for omitted media files. Default is " media_omitted "
#' @export
#' @importFrom qdapRegex rm_default
#' @importFrom stringi stri_split_fixed
#' @importFrom lubridate parse_date_time
#' @importFrom stringi stri_split_regex
#' @importFrom stringr str_extract_all
#' @return A dataframe containing the timestamp, name of the sender and message body
#' @examples
#' ParsedChat <- parse_ios("[29.01.18, 23:33:00] Alice: Hello?\\n [29.01.18, 23:45:01] Bob: Hello")

parse_ios <- function(UnparsedChat,
                     nl = "\n",
                     mediaomitted = "<media omitted>",
                     mediaindicator =	"^<attached:\\s(.)*?\\.(.)*?>$",
                     sentlocation = paste0("Location: (?=https:\\/\\/maps\\.google\\.com\\/",
                                           "\\?q=\\d\\d.\\d{6}\\,\\d\\.\\d{6})"),
                     livelocation =  "^live location shared$",
                     datetimeindicator = paste("(?!^)(?=\\[((\\d{2}\\.\\d{2}\\.\\d{2})|",
                     "(\\d{1,2}\\/\\d{1,2}\\/\\d{2})),\\s\\d{1,2}\\:\\d{2}((\\:\\d{2}\\",
                     "s(?i:(pm|am)))|(\\s(?i:(pm|am)))|(\\:\\d{2}\\])|(\\:\\d{2})|(\\s))\\])",sep=""),
                     nlreplace = " start_newline ",
                     mediareplace = " media_omitted "){

  # Deleting string for omitted media "<Media omitted>" and the positioning unicode
  # for present media data
  chatA <- gsub(pattern = mediaomitted,
                UnparsedChat,
                replacement = mediareplace,
                perl = TRUE)

  # Cutting the textblock into individual messages (cut in front of the datetime)
  chat4 <- strsplit(chatA,datetimeindicator,perl=TRUE)
  chat4 <- unlist(chat4)

  # Replacing newline within messages
  chat5 <- rm_default(chat4,
                      pattern = nlreplace)

  ### We cut the message to form vectors for datetime, sender and the actual message

  # Splitting
  DateSplit <- stri_split_fixed(str = chat5,
                                pattern = "]",
                                n = 2)

  SenderSplit <- stri_split_fixed(str = sapply(DateSplit, "[", 2),
                                  pattern = ": ",
                                  n = 2)

  # Extract DateTime and encode correctly
  DateTime <- sapply(DateSplit, function(x){x[1]})
  DateTime <- substring(DateTime,2)

  # Setting orders for time parsing
  timestrings <- c("dmy, HMS",
              "dmy, HM",
              "dmy, IMp",
              "dmy, IMSp",
              "mdy, HMS",
              "mdy, HM",
              "mdy, IMp",
              "mdy, IMSp")

  # parsing datetime
  DateTime <- parse_date_time(DateTime,
                              orders = timestrings,
                              select_formats = TRUE)

  # Extract Sender and encode correctly
  Sender <- sapply(SenderSplit, "[", 1)
  Sender <- trimws(Sender)

  # Extract Message
  Message <- sapply(SenderSplit, "[", 2)

  ###### Media

  # removing indicator string for attached files
  Media <- stri_split_regex(str = Message, pattern = mediaindicator, n = 2)
  Media[which(sapply(Media,length) == 1)] <- NA
  Media <- sapply(Media, "[", 2)
  Media <- substr(Media,1,nchar(Media)-1)

  # extract location to column
  Location <- str_extract_all(Message, pattern = paste(c(livelocation,sentlocation), collapse = "|"))
  Location[sapply(Location, length) == 0] <- NA
  Location <- unlist(Location)

  # binding the columns together
  Result <- cbind.data.frame(DateTime,
                             Sender,
                             Message,
                             Media,
                             Location,
                             stringsAsFactors = FALSE)

  # returning parsed Result
  return(Result)

}
