#' @title Parsing raw WhatsApp Chat Textfiles accoring to Android text structure
#'
#' @description Creates a dataframe from an exported WhatsApp textfile containing one row per message
#' and a column for DateTime when the message was send, name of the sender and body of the message.
#' @param UnparsedChat the name of the exported Whatsapp textfile to be parsed as a character string
#' @param nl character string defining character for newline indicators. Default is a unicode newline
#' @param mediaindicator character string for detecting media and file attachments
#' @param mediaomitted character string inserted by WhatsApp instead of filenames when not exporting media
#' @param sentlocation Regex for detecting autogenerated messages for locations shared via chat
#' @param livelocation Regex for detecting autogenerated messages for live locations shared via chat
#' @param datetimeindicator Regex for detecting the DateTime indicator at the beginning of each message
#' @param nlreplace replacement string for a newline character in parsed message. Default is " START_NEWLINE "
#' @param mediareplace replacement string for omitted media files. Default is " media_omitted "
#' @export
#' @importFrom qdapRegex rm_default
#' @importFrom stringi stri_split_fixed
#' @importFrom lubridate parse_date_time
#' @importFrom stringi stri_split_regex
#' @importFrom stringr str_extract_all
#' @return A dataframe containing the timestamp, name of the sender and message body
#' @examples
#' ParsedChat <- ParseAndroid("29.01.18, 23:33 - Alice: Hi?\n 29.01.18, 23:45 - Bob: Hi\n")

ParseAndroid <- function(UnparsedChat,
                         nl = "\n",
                         mediaomitted = "<media omitted>",
                         mediaindicator =	"(file attached)",
                         sentlocation = paste0("Location: (?=https:\\/\\/maps\\.google\\.com\\/",
                                               "\\?q=\\d\\d.\\d{6}\\,\\d\\.\\d{6})"),
                         livelocation =  "^live location shared$",
                         datetimeindicator = paste("(?!^)(?=((\\d{2}\\.\\d{2}\\.\\d{2})|(\\d{1,2}",
                         "\\/\\d{1,2}\\/\\d{2})),\\s\\d{2}\\:\\d{2}((\\s\\-)|(\\s(?i:(am|pm))\\s\\-)))",sep=""),
                         nlreplace = " start_newline ",
                         mediareplace = " media_omitted "){

  # Replaceing string for omitted media
  chatA <- gsub(pattern = mediaomitted,
                UnparsedChat,
                replacement = mediareplace,
                perl = TRUE)

  # Cutting the messages in front of the datetime indicator
  chat4 <- unlist(strsplit(str_replace_all(chatA,datetimeindicator,"SPLIT-INDICATOR"),
                           "SPLIT-INDICATOR"))

  # deleting trailing Linebreakes (simply deletes the last character)
  chat5 <- substr(chat4,1,nchar(as.character(chat4))-1)

  # Replacing Linebreaks within messages
  chat6 <- rm_default(chat5,
                      pattern = nl,
                      replacement= nlreplace)

  ### We cut the message to form vectors for datetime, sender and the actual message

  # Splitting
  DateSplit <- stri_split_fixed(str = chat6,
                                pattern = " - ",
                                n = 2)

  SenderSplit <- stri_split_fixed(str = sapply(DateSplit, "[", 2),
                                  pattern = ": ",
                                  n = 2)

  # Extract DateTime and encode correctly
  DateTime <- sapply(DateSplit, function(x){x[1]})

  # Defining Time orders for lubridate::parse_date_time() function
  timestrings <- c("dmy, HMS",
                   "dmy, HM",
                   "dmy, IMp",
                   "dmy, IMSp",
                   "mdy, HMS",
                   "mdy, HM",
                   "mdy, IMp",
                   "mdy, IMSp")

  DateTime <- parse_date_time(DateTime,
                              orders = timestrings,
                              select_formats = TRUE)

  # Extract Sender and encode correctly
  Sender <- sapply(SenderSplit, "[", 1)

  # Extract Message
  Message <- sapply(SenderSplit, "[", 2)

  ###### Media

  # removing indicator string for attached files
  Media <- stri_split_regex(str = Message, pattern = mediaindicator, n = 2)
  Media[which(sapply(Media,length) == 1)] <- NA # This will assign everything to be NA if there is no NA list element in the Media string (fix later)
  Media <- sapply(Media, "[", 1)

  # Deleting trailing characters
  Media[!is.na(Media)] <- substr(Media[!is.na(Media)],1,nchar(Media[!is.na(Media)])-2)

  # extract location to column
  Location <- str_extract_all(Message, pattern = paste(c(livelocation,sentlocation), collapse = "|"))
  Location[sapply(Location, length) == 0] <- NA
  Location <- unlist(Location)

  # binding the columns together
  Result <- cbind.data.frame(DateTime,
                             Sender,
                             Message,
                             Media,
                             Location,
                             stringsAsFactors = FALSE)

  # returning parsed Result
  return(Result)

}
